

export type FirebaseAuthError = {
  code: string;
  message: string;
};

export const FirebaseAuthErrorCodes = {
  CLAIMS_TOO_LARGE: 'auth/claims-too-large',
  EMAIL_ALREADY_EXISTS: 'auth/email-already-exists',
  ID_TOKEN_EXPIRED: 'auth/id-token-expired',
  ID_TOKEN_REVOKED: 'auth/id-token-revoked',
  INSUFFICIENT_PERMISSION: 'auth/insufficient-permission',
  INTERNAL_ERROR: 'auth/internal-error',
  INVALID_ARGUMENT: 'auth/invalid-argument',
  INVALID_CLAIMS: 'auth/invalid-claims',
  INVALID_CONTINUE_URI: 'auth/invalid-continue-uri',
  INVALID_CREATION_TIME: 'auth/invalid-creation-time',
  INVALID_CREDENTIAL: 'auth/invalid-credential',
  INVALID_DISABLED_FIELD: 'auth/invalid-disabled-field',
  INVALID_DISPLAY_NAME: 'auth/invalid-display-name',
  INVALID_DYNAMIC_LINK_DOMAIN: 'auth/invalid-dynamic-link-domain',
  INVALID_EMAIL: 'auth/invalid-email',
  INVALID_EMAIL_VERIFIED: 'auth/invalid-email-verified',
  INVALID_HASH_ALGORITHM: 'auth/invalid-hash-algorithm',
  INVALID_HASH_BLOCK_SIZE: 'auth/invalid-hash-block-size',
  INVALID_HASH_DERIVED_KEY_LENGTH: 'auth/invalid-hash-derived-key-length',
  INVALID_HASH_KEY: 'auth/invalid-hash-key',
  INVALID_HASH_MEMORY_COST: 'auth/invalid-hash-memory-cost',
  INVALID_HASH_PARALLELIZATION: 'auth/invalid-hash-parallelization',
  INVALID_HASH_ROUNDS: 'auth/invalid-hash-rounds',
  INVALID_HASH_SALT_SEPARATOR: 'auth/invalid-hash-salt-separator',
  INVALID_ID_TOKEN: 'auth/invalid-id-token',
  INVALID_LAST_SIGN_IN_TIME: 'auth/invalid-last-sign-in-time',
  INVALID_PAGE_TOKEN: 'auth/invalid-page-token',
  INVALID_PASSWORD: 'auth/invalid-password',
  INVALID_PASSWORD_HASH: 'auth/invalid-password-hash',
  INVALID_PASSWORD_SALT: 'auth/invalid-password-salt',
  INVALID_PHONE_NUMBER: 'auth/invalid-phone-number',
  INVALID_PHOTO_URL: 'auth/invalid-photo-url',
  INVALID_PROVIDER_DATA: 'auth/invalid-provider-data',
  INVALID_PROVIDER_ID: 'auth/invalid-provider-id',
  INVALID_OAUTH_RESPONSETYPE: 'auth/invalid-oauth-responsetype',
  INVALID_SESSION_COOKIE_DURATION: 'auth/invalid-session-cookie-duration',
  INVALID_UID: 'auth/invalid-uid',
  INVALID_USER_IMPORT: 'auth/invalid-user-import',
  MAXIMUM_USER_COUNT_EXCEEDED: 'auth/maximum-user-count-exceeded',
  MISSING_ANDROID_PKG_NAME: 'auth/missing-android-pkg-name',
  MISSING_CONTINUE_URI: 'auth/missing-continue-uri',
  MISSING_HASH_ALGORITHM: 'auth/missing-hash-algorithm',
  MISSING_IOS_BUNDLE_ID: 'auth/missing-ios-bundle-id',
  MISSING_UID: 'auth/missing-uid',
  MISSING_OAUTH_CLIENT_SECRET: 'auth/missing-oauth-client-secret',
  OPERATION_NOT_ALLOWED: 'auth/operation-not-allowed',
  PHONE_NUMBER_ALREADY_EXISTS: 'auth/phone-number-already-exists',
  PROJECT_NOT_FOUND: 'auth/project-not-found',
  RESERVED_CLAIMS: 'auth/reserved-claims',
  SESSION_COOKIE_EXPIRED: 'auth/session-cookie-expired',
  SESSION_COOKIE_REVOKED: 'auth/session-cookie-revoked',
  TOO_MANY_REQUESTS: 'auth/too-many-requests',
  UID_ALREADY_EXISTS: 'auth/uid-already-exists',
  UNAUTHORIZED_CONTINUE_URI: 'auth/unauthorized-continue-uri',
  USER_NOT_FOUND: 'auth/user-not-found',
};

type FirebaseAuthErrorMessages = {
  [key in keyof typeof FirebaseAuthErrorCodes]: string;
};

export const firebaseAuthErrorMessages: FirebaseAuthErrorMessages = {
  CLAIMS_TOO_LARGE: '제공된 클레임 페이로드가 최대 허용 크기인 1,000바이트를 초과합니다.',
  EMAIL_ALREADY_EXISTS: '제공된 이메일을 기존 사용자가 이미 사용 중입니다. 이메일은 고유해야 합니다.',
  ID_TOKEN_EXPIRED: '제공된 Firebase ID 토큰이 만료되었습니다.',
  ID_TOKEN_REVOKED: 'Firebase ID 토큰이 취소되었습니다.',
  INSUFFICIENT_PERMISSION: '이 인증 정보로는 요청한 작업을 수행할 권한이 없습니다.',
  INTERNAL_ERROR: '예기치 않은 오류가 발생했습니다. 다시 시도해 주세요.',
  INVALID_ARGUMENT: '잘못된 인자가 제공되었습니다. 제공된 인수를 확인해 주세요.',
  INVALID_CLAIMS: '잘못된 커스텀 클레임 속성이 제공되었습니다.',
  INVALID_CONTINUE_URI: '연결 URL이 올바르지 않습니다.',
  INVALID_CREATION_TIME: '생성 시간은 UTC 날짜 형식이어야 합니다.',
  INVALID_CREDENTIAL: '잘못된 인증 정보가 제공되었습니다.',
  INVALID_DISABLED_FIELD: 'disabled 속성 값이 잘못되었습니다. 이 값은 부울이어야 합니다.',
  INVALID_DISPLAY_NAME: 'displayName 속성 값이 잘못되었습니다. 이 값은 비어 있지 않은 문자열이어야 합니다.',
  INVALID_DYNAMIC_LINK_DOMAIN: '제공된 동적 링크 도메인이 올바르지 않습니다.',
  INVALID_EMAIL: '잘못된 이메일 주소입니다.',
  INVALID_EMAIL_VERIFIED: 'emailVerified 속성 값이 잘못되었습니다. 이 값은 부울이어야 합니다.',
  INVALID_HASH_ALGORITHM: '지원되지 않는 해시 알고리즘이 사용되었습니다.',
  INVALID_HASH_BLOCK_SIZE: '해시 블록 크기가 올바르지 않습니다.',
  INVALID_HASH_DERIVED_KEY_LENGTH: '해시에서 파생된 키 길이가 올바르지 않습니다.',
  INVALID_HASH_KEY: '해시 키가 잘못되었습니다.',
  INVALID_HASH_MEMORY_COST: '해시 메모리 비용이 올바르지 않습니다.',
  INVALID_HASH_PARALLELIZATION: '해시 병렬화 값이 올바르지 않습니다.',
  INVALID_HASH_ROUNDS: '해시 라운드 값이 올바르지 않습니다.',
  INVALID_HASH_SALT_SEPARATOR: '해시 솔트 구분자 값이 올바르지 않습니다.',
  INVALID_ID_TOKEN: '잘못된 Firebase ID 토큰이 제공되었습니다.',
  INVALID_LAST_SIGN_IN_TIME: '마지막 로그인 시간이 올바르지 않습니다.',
  INVALID_PAGE_TOKEN: '페이지 토큰이 잘못되었습니다.',
  INVALID_PASSWORD: '비밀번호는 최소 6자 이상이어야 합니다.',
  INVALID_PASSWORD_HASH: '비밀번호 해시가 올바르지 않습니다.',
  INVALID_PASSWORD_SALT: '비밀번호 솔트가 올바르지 않습니다.',
  INVALID_PHONE_NUMBER: '전화번호는 E.164 표준을 준수해야 합니다.',
  INVALID_PHOTO_URL: 'photoURL 값이 잘못되었습니다. 유효한 URL이어야 합니다.',
  INVALID_PROVIDER_DATA: 'providerData가 올바른 형태가 아닙니다.',
  INVALID_PROVIDER_ID: 'providerId가 잘못되었습니다.',
  INVALID_OAUTH_RESPONSETYPE: 'OAuth responseType 설정이 잘못되었습니다.',
  INVALID_SESSION_COOKIE_DURATION: '세션 쿠키 기간이 잘못되었습니다.',
  INVALID_UID: 'UID 값이 잘못되었습니다. 128자 이하이어야 합니다.',
  INVALID_USER_IMPORT: '사용자 레코드가 잘못되었습니다.',
  MAXIMUM_USER_COUNT_EXCEEDED: '가져올 수 있는 최대 사용자 수를 초과했습니다.',
  MISSING_ANDROID_PKG_NAME: 'Android 패키지 이름이 누락되었습니다.',
  MISSING_CONTINUE_URI: '연결 URL이 누락되었습니다.',
  MISSING_HASH_ALGORITHM: '해시 알고리즘이 누락되었습니다.',
  MISSING_IOS_BUNDLE_ID: 'iOS 번들 ID가 누락되었습니다.',
  MISSING_UID: 'UID가 누락되었습니다.',
  MISSING_OAUTH_CLIENT_SECRET: 'OAuth 클라이언트 비밀번호가 누락되었습니다.',
  OPERATION_NOT_ALLOWED: '이 로그인 방법은 사용 설정되지 않았습니다.',
  PHONE_NUMBER_ALREADY_EXISTS: '제공된 전화번호는 이미 사용 중입니다.',
  PROJECT_NOT_FOUND: 'Firebase 프로젝트를 찾을 수 없습니다.',
  RESERVED_CLAIMS: '예약된 커스텀 클레임이 포함되어 있습니다.',
  SESSION_COOKIE_EXPIRED: '세션 쿠키가 만료되었습니다.',
  SESSION_COOKIE_REVOKED: '세션 쿠키가 취소되었습니다.',
  TOO_MANY_REQUESTS: '요청 수가 너무 많습니다. 잠시 후 다시 시도해 주세요.',
  UID_ALREADY_EXISTS: '제공된 UID는 이미 사용 중입니다.',
  UNAUTHORIZED_CONTINUE_URI: '연결 URL이 허용되지 않은 도메인입니다.',
  USER_NOT_FOUND: '사용자를 찾을 수 없습니다.',
};

export const getFirebaseAuthErrorMessage = (code: string): string => {
  return firebaseAuthErrorMessages[code as keyof typeof firebaseAuthErrorMessages] || '알 수 없는 오류가 발생했습니다.';
};
